/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.cmartinez.view;

import cl.duoc.cmartinez.controller.MainController;
import java.awt.event.ActionListener;
import java.sql.Date;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinezs
 */
public class LibraryView extends javax.swing.JFrame {

    /**
     * Creates new form LibraryView
     */
    public LibraryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        tableStock = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        addBookPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblPublication = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtPublication = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        chkAvailability = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuInventory = new javax.swing.JMenu();
        menuLibraryItemStock = new javax.swing.JMenuItem();
        menuLibraryItemAddBook = new javax.swing.JMenuItem();
        menuActions = new javax.swing.JMenu();

        lblHeader1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblHeader1.setText("STOCK OF BOOKS");

        tableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Author", "Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableStock.setColumnSelectionAllowed(true);
        tableStock.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(tableStock);
        tableStock.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnDelete.setText("Delete");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addComponent(lblHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader1)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblHeader.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblHeader.setText("NEW BOOK");

        lblAuthor.setText("Author");

        lblTitle.setText("Title");

        lblIsbn.setText("ISBN");

        lblPublication.setText("Publication");

        lblPrice.setText("Price");

        lblAvailability.setText("Availability");

        chkAvailability.setText("yes");

        btnSave.setText("Save");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout addBookPanelLayout = new javax.swing.GroupLayout(addBookPanel);
        addBookPanel.setLayout(addBookPanelLayout);
        addBookPanelLayout.setHorizontalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAvailability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPublication, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIsbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublication, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txtIsbn)
                            .addComponent(txtTitle)
                            .addComponent(txtAuthor)
                            .addComponent(txtPrice)
                            .addGroup(addBookPanelLayout.createSequentialGroup()
                                .addComponent(chkAvailability)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBookPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        addBookPanelLayout.setVerticalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublication)
                    .addComponent(txtPublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(chkAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library");

        mainPanel.setLayout(new java.awt.CardLayout());

        menuInventory.setText("Inventory");

        menuLibraryItemStock.setText("Stock");
        menuInventory.add(menuLibraryItemStock);

        menuLibraryItemAddBook.setText("Add book");
        menuLibraryItemAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLibraryItemAddBookActionPerformed(evt);
            }
        });
        menuInventory.add(menuLibraryItemAddBook);

        menuBar.add(menuInventory);

        menuActions.setText("Actions");
        menuBar.add(menuActions);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLibraryItemAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLibraryItemAddBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLibraryItemAddBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPublication;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuActions;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuInventory;
    private javax.swing.JMenuItem menuLibraryItemAddBook;
    private javax.swing.JMenuItem menuLibraryItemStock;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable tableStock;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPublication;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    public void addActionListenerMenuItemLibraryStock(ActionListener ac) {
        menuLibraryItemStock.addActionListener(ac);
    }

    public void addActionListenerMenuItemLibraryAddBook(ActionListener ac) {
        menuLibraryItemAddBook.addActionListener(ac);
    }

    public void setVisibleTableBook() {
        removeComponentsMainPanel();
        mainPanel.add(tablePanel, "CardLayout");
        mainPanel.setVisible(true);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void setVisibleFormAddBook() {
        removeComponentsMainPanel();
        mainPanel.add(addBookPanel, "CardLayout");
        mainPanel.setVisible(true);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void removeComponentsMainPanel() {
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void addRowToBookTable(String isbn, String author, String title) {
        DefaultTableModel temp = (DefaultTableModel) tableStock.getModel();
        temp.addRow(new Object[]{isbn, author, title});
    }

    public void cleanTableBook() {
        DefaultTableModel dtm = (DefaultTableModel) tableStock.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    public void addActionListenerAddBookPanelBtnCancel(ActionListener ac) {
        btnCancel.addActionListener(ac);
    }

    public void addActionListenerAddBookPanelBtnSave(ActionListener ac) {
        btnSave.addActionListener(ac);
    }

    public void addActionListenerStockPanelBtnDelete(ActionListener ac) {
        btnDelete.addActionListener(ac);
    }

    public String getAuthor() {
        return txtAuthor.getText();
    }

    public String getBookTitle() {
        return txtTitle.getText();
    }

    public String getISBN() {
        return txtIsbn.getText();
    }

    /*public Date getPublication() {
        return txtPublication.getText();
    }*/

    public double getPrice() {
        return Double.parseDouble(txtPrice.getText());
    }

    public boolean getAvailability() {
        return chkAvailability.isSelected();
    }

    public void clickMenuItemStock() {
        menuLibraryItemStock.doClick();
    }

    public String getSelectedIsbnInBookTable() {
        DefaultTableModel temp = (DefaultTableModel) tableStock.getModel();
        int row = tableStock.getSelectedRow();
        if(row < 0){
            System.out.println("No hay fila");
            return "";
        }
        
        Object obj = temp.getValueAt(row, 0);
        System.out.println("Selected: " + obj);
        return (String)obj;
    }
}
